package lab2;
import java.util.Scanner;
public class q3 {
    public static Scanner sc;
    /**
     * This program generates an abbreviation for a given string input. 
     * The abbreviation is generated by taking the first letter of the input string and adding a period. 
     * Then, the program looks for the second word in the input string and takes the first letter of that word and adds it to the abbreviation. 
     * The program then continues to look for the next word and takes the first letter of that word and adds it to the abbreviation until it has found two words. 
     * Finally, the program prints the abbreviation followed by the remaining characters of the input string.
     * 
     */
    public static void main(String[] args) {
        System.out.println("Enter String:");
        sc = new Scanner(System.in);
        String inputString= sc.nextLine();
        char a=(inputString.charAt(0));
        String abbravation_generated;
        abbravation_generated=String.valueOf(a);
        abbravation_generated=abbravation_generated.concat(".");
        int positon=0,inx=0;
        for(int i=1;i<inputString.length() && positon != 2;i++){

            if(' ' == inputString.charAt(i) && positon==1){
                inx=i+1;
                positon=2;
            }
            if(' ' == inputString.charAt(i) && positon==0){
                abbravation_generated=abbravation_generated.concat(String.valueOf(inputString.charAt(i+1)));

                abbravation_generated=abbravation_generated.concat(".");
                positon=1;
            }
        }
        System.out.print(abbravation_generated);
        for(int i=inx;i<inputString.length();i++){
            System.out.print(inputString.charAt(i));
        }
        System.out.print('\n');
        
    }
}
